#!/usr/bin/env python3
"""
Render IR into JSONL chunks for RAG.

Inputs:
  - <bundle_dir>/<bundle_name>_ir.json  (generated by build_ir.py)

Outputs:
  - <out>/<bundle_name>_docs.jsonl

Chunk types emitted:
  - entity_header
  - entity_fields
  - entity_constraints
  - entity_relationships
  - field_fact
  - glossary (optional)
  - entity_inline (optional, only for configured roots)

Usage:
  python render_chunks.py /path/to/bundle
  python render_chunks.py /path/to/bundle --out /path/to/out
  python render_chunks.py /path/to/bundle --max-fields-per-chunk 25
  python render_chunks.py /path/to/bundle --emit-inline --inline-roots "FxSwap,FxForward" --inline-max-depth 8
  python render_chunks.py /path/to/bundle --no-field-facts --no-glossary
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

Json = Dict[str, Any]


# ----------------------------
# Helpers
# ----------------------------

def read_json(path: Path) -> Json:
    return json.loads(path.read_text(encoding="utf-8"))


def write_jsonl(path: Path, docs: Iterable[Json]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for d in docs:
            f.write(json.dumps(d, ensure_ascii=False) + "\n")


def safe(s: str) -> str:
    s = s.strip()
    s = re.sub(r"\s+", "_", s)
    s = re.sub(r"[^A-Za-z0-9_.:#/-]+", "_", s)
    return s


def is_ref_typeref(t: Any) -> Optional[str]:
    if isinstance(t, dict) and isinstance(t.get("ref"), str):
        return t["ref"]
    return None


def cardinality_str(card: Optional[dict]) -> str:
    if not isinstance(card, dict):
        return ""
    mi = card.get("min", 0)
    ma = card.get("max", None)
    if ma is None:
        return f"[{mi}..*]"
    return f"[{mi}..{ma}]"


def short_id(eid: str) -> str:
    # For display only: try to show suffix after last '#', else last segment.
    if "#" in eid:
        return eid.split("#")[-1]
    parts = re.split(r"[/:]+", eid)
    return parts[-1] if parts else eid


def normalize_name(entity: dict) -> str:
    n = entity.get("name")
    if isinstance(n, str) and n.strip():
        return n.strip()
    return short_id(entity.get("id", "unknown"))


def collect_provenance(entity: dict) -> List[dict]:
    prov = entity.get("provenance") or []
    return [p for p in prov if isinstance(p, dict)]


def collect_source_files(entity: dict) -> List[str]:
    files: Set[str] = set()
    ann = entity.get("annotations") or {}
    if isinstance(ann, dict):
        sf = ann.get("source_file")
        if isinstance(sf, str) and sf.strip():
            files.add(sf.strip())

    # also look in provenance.locator
    for p in collect_provenance(entity):
        loc = p.get("locator")
        if isinstance(loc, str) and loc.strip():
            # loc may contain "file :: pointer" - keep only file-ish part
            files.add(loc.split(" :: ")[0].strip())
    return sorted(files)


def entity_refs(entity: dict) -> Set[str]:
    refs: Set[str] = set()

    # extends
    for x in entity.get("extends") or []:
        rid = is_ref_typeref(x)
        if rid:
            refs.add(rid)

    # fields
    for f in entity.get("fields") or []:
        if not isinstance(f, dict):
            continue
        rid = is_ref_typeref(f.get("type"))
        if rid:
            refs.add(rid)

    # array element
    rid = is_ref_typeref(entity.get("elementType"))
    if rid:
        refs.add(rid)

    # union choice options
    ch = entity.get("choice")
    if isinstance(ch, dict):
        for opt in ch.get("options") or []:
            rid2 = is_ref_typeref(opt)
            if rid2:
                refs.add(rid2)

    return refs


def estimate_len(text: str) -> int:
    # Simple char-based estimate; good enough for chunk sizing.
    return len(text)


# ----------------------------
# Rendering
# ----------------------------

def render_entity_header(bundle: dict, entity: dict) -> str:
    bn = bundle.get("name", "")
    sid = bundle.get("source_id", "")
    ver = bundle.get("version", "")
    kind = entity.get("kind", "")
    name = normalize_name(entity)
    eid = entity.get("id", "")

    src_files = collect_source_files(entity)
    provs = collect_provenance(entity)
    prov_line = ""
    if src_files:
        prov_line = f"Source files: {', '.join(src_files)}"
    elif provs:
        locs = [p.get("locator") for p in provs if isinstance(p.get("locator"), str)]
        if locs:
            prov_line = f"Provenance: {locs[0]}"

    desc = entity.get("description")
    desc_txt = desc.strip() if isinstance(desc, str) and desc.strip() else ""

    lines = []
    lines.append(f"# Entity: {name}")
    lines.append(f"EntityId: {eid}")
    lines.append(f"Bundle: {bn} | Source: {sid} {ver} | Kind: {kind}")
    if prov_line:
        lines.append(prov_line)
    if desc_txt:
        lines.append("")
        lines.append("Description:")
        lines.append(desc_txt)
    return "\n".join(lines).strip() + "\n"


def render_field_line(field: dict) -> str:
    fname = field.get("name", "")
    ftype = field.get("type", "any")
    card = field.get("cardinality")
    req = field.get("required")
    req_txt = ""
    if isinstance(req, bool):
        req_txt = " required" if req else ""

    type_txt = ""
    rid = is_ref_typeref(ftype)
    if rid:
        type_txt = f"ref:{short_id(rid)}"
    elif isinstance(ftype, str):
        type_txt = ftype
    else:
        type_txt = "any"

    c = cardinality_str(card)
    line = f"- {fname} : {type_txt} {c}{req_txt}".rstrip()
    return line


def render_field_details(field: dict) -> List[str]:
    out: List[str] = []
    desc = field.get("description")
    if isinstance(desc, str) and desc.strip():
        out.append(f"  - description: {desc.strip()}")

    constraints = field.get("constraints") or []
    if isinstance(constraints, list) and constraints:
        # keep it short; detailed constraints appear in entity_constraints chunk
        kinds = []
        for c in constraints:
            if isinstance(c, dict) and isinstance(c.get("kind"), str):
                kinds.append(c["kind"])
        if kinds:
            out.append(f"  - constraints: {', '.join(sorted(set(kinds)))}")

    ex = field.get("examples") or []
    if isinstance(ex, list) and ex:
        # show up to 2 examples
        ex2 = ex[:2]
        out.append(f"  - examples: {json.dumps(ex2, ensure_ascii=False)}")
    return out


def render_entity_fields_chunk(bundle: dict, entity: dict, fields: List[dict], idx: int, total: int) -> str:
    name = normalize_name(entity)
    lines = []
    lines.append(f"## Fields for {name} ({idx}/{total})")
    for f in fields:
        if not isinstance(f, dict):
            continue
        lines.append(render_field_line(f))
        lines.extend(render_field_details(f))
    return "\n".join(lines).strip() + "\n"


def render_constraints_block(title: str, constraints: List[dict]) -> str:
    lines = []
    lines.append(title)
    for c in constraints:
        if not isinstance(c, dict):
            continue
        kind = c.get("kind", "constraint")
        target = c.get("target")
        pieces = [f"- kind={kind}"]
        if isinstance(target, str) and target.strip():
            pieces.append(f"target={target}")
        if "values" in c:
            v = c.get("values")
            if isinstance(v, list):
                pieces.append(f"values={v[:20]}{'...' if len(v) > 20 else ''}")
        if isinstance(c.get("pattern"), str):
            pieces.append(f"pattern={c['pattern']}")
        if c.get("minimum") is not None or c.get("maximum") is not None:
            pieces.append(f"range=[{c.get('minimum')},{c.get('maximum')}]")
        if c.get("minLength") is not None or c.get("maxLength") is not None:
            pieces.append(f"length=[{c.get('minLength')},{c.get('maxLength')}]")
        if isinstance(c.get("format"), str):
            pieces.append(f"format={c['format']}")
        if "const" in c:
            pieces.append(f"const={c.get('const')}")
        if isinstance(c.get("message"), str):
            pieces.append(f"message={c['message']}")
        lines.append("  " + " ".join(pieces))
    return "\n".join(lines).strip() + "\n"


def render_entity_constraints(bundle: dict, entity: dict) -> str:
    # collect entity + field constraints
    all_constraints: List[dict] = []
    ent_constraints = entity.get("constraints") or []
    if isinstance(ent_constraints, list):
        all_constraints.extend([c for c in ent_constraints if isinstance(c, dict)])

    for f in entity.get("fields") or []:
        if not isinstance(f, dict):
            continue
        fc = f.get("constraints") or []
        if isinstance(fc, list):
            for c in fc:
                if isinstance(c, dict):
                    # ensure target has some path
                    if "target" not in c and isinstance(f.get("name"), str):
                        c = dict(c)
                        c["target"] = f"{normalize_name(entity)}.{f['name']}"
                    all_constraints.append(c)

    if not all_constraints:
        return ""

    name = normalize_name(entity)
    return render_constraints_block(f"## Constraints for {name}", all_constraints)


def render_entity_relationships(bundle: dict, entity: dict) -> str:
    refs = sorted(entity_refs(entity))
    extends = entity.get("extends") or []
    name = normalize_name(entity)

    lines = []
    lines.append(f"## Relationships for {name}")

    if extends:
        lines.append("Extends:")
        for ex in extends:
            rid = is_ref_typeref(ex)
            if rid:
                lines.append(f"- ref:{rid}")
            else:
                lines.append(f"- {ex}")

    if refs:
        lines.append("References:")
        for r in refs:
            lines.append(f"- {r}")

    # provenance summary
    src_files = collect_source_files(entity)
    if src_files:
        lines.append("Provenance files:")
        for sf in src_files:
            lines.append(f"- {sf}")

    return "\n".join(lines).strip() + "\n"


def render_field_fact(bundle: dict, entity: dict, field: dict) -> Optional[str]:
    if not isinstance(field, dict):
        return None
    ename = normalize_name(entity)
    fname = field.get("name")
    if not isinstance(fname, str) or not fname.strip():
        return None

    path = f"{ename}.{fname}"
    ftype = field.get("type", "any")
    rid = is_ref_typeref(ftype)
    type_txt = f"ref:{short_id(rid)}" if rid else (ftype if isinstance(ftype, str) else "any")
    c = cardinality_str(field.get("cardinality"))

    lines = []
    lines.append(f"# Field: {path}")
    lines.append(f"Type: {type_txt} {c}".rstrip())

    desc = field.get("description")
    if isinstance(desc, str) and desc.strip():
        lines.append(f"Description: {desc.strip()}")

    cons = field.get("constraints") or []
    if isinstance(cons, list) and cons:
        # concise constraint summary
        kinds = []
        for cc in cons:
            if isinstance(cc, dict) and isinstance(cc.get("kind"), str):
                kinds.append(cc["kind"])
        if kinds:
            lines.append(f"Constraints: {', '.join(sorted(set(kinds)))}")

    # provenance hint
    provs = field.get("provenance") or []
    if isinstance(provs, list) and provs:
        locs = [p.get("locator") for p in provs if isinstance(p, dict) and isinstance(p.get("locator"), str)]
        if locs:
            lines.append(f"Provenance: {locs[0]}")

    return "\n".join(lines).strip() + "\n"


def render_glossary(bundle: dict, entities: List[dict], max_chars: int) -> List[str]:
    # return one or more glossary chunks
    items = []
    for e in entities:
        if not isinstance(e, dict):
            continue
        name = normalize_name(e)
        eid = e.get("id", "")
        kind = e.get("kind", "")
        desc = e.get("description", "")
        desc_short = (desc.strip()[:120] + "…") if isinstance(desc, str) and len(desc.strip()) > 120 else (desc.strip() if isinstance(desc, str) else "")
        items.append((name.lower(), name, eid, kind, desc_short))

    items.sort(key=lambda t: t[0])

    chunks: List[str] = []
    cur_lines: List[str] = []
    cur_lines.append("# Glossary")
    cur_lines.append(f"Bundle: {bundle.get('name','')}")
    cur_len = estimate_len("\n".join(cur_lines)) + 1

    for _, name, eid, kind, desc_short in items:
        line = f"- {name} ({kind}) id={eid}"
        if desc_short:
            line += f" — {desc_short}"
        add_len = estimate_len(line) + 1
        if cur_len + add_len > max_chars and len(cur_lines) > 3:
            chunks.append("\n".join(cur_lines).strip() + "\n")
            cur_lines = ["# Glossary (cont.)", f"Bundle: {bundle.get('name','')}"]
            cur_len = estimate_len("\n".join(cur_lines)) + 1
        cur_lines.append(line)
        cur_len += add_len

    if cur_lines:
        chunks.append("\n".join(cur_lines).strip() + "\n")

    return chunks


# ----------------------------
# Inline rendering
# ----------------------------

def render_inline_tree(inline_obj: Any, indent: int = 0, max_lines: int = 2000) -> List[str]:
    """
    Render entity.annotations.inline structure into a compact, readable outline.
    This is deterministic and safe for large structures (bounded by max_lines).
    """
    lines: List[str] = []
    prefix = "  " * indent

    if len(lines) >= max_lines:
        return lines

    if isinstance(inline_obj, dict) and "ref" in inline_obj and isinstance(inline_obj["ref"], str):
        ann = inline_obj.get("annotations") or {}
        if isinstance(ann, dict) and ann.get("cycle") is True:
            lines.append(prefix + f"- ref:{short_id(inline_obj['ref'])} (cycle)")
        elif isinstance(ann, dict) and ann.get("depth_cutoff") is True:
            lines.append(prefix + f"- ref:{short_id(inline_obj['ref'])} (depth_cutoff)")
        else:
            lines.append(prefix + f"- ref:{short_id(inline_obj['ref'])}")
        return lines

    if not isinstance(inline_obj, dict):
        lines.append(prefix + f"- {str(inline_obj)}")
        return lines

    kind = inline_obj.get("kind", "")
    name = inline_obj.get("name") or short_id(inline_obj.get("id", ""))
    lines.append(prefix + f"- {name} ({kind})")

    # fields
    fields = inline_obj.get("fields") or []
    if isinstance(fields, list) and fields:
        for f in fields:
            if not isinstance(f, dict):
                continue
            fname = f.get("name", "")
            ftype = f.get("type")
            card = f.get("cardinality")
            c = cardinality_str(card)
            if isinstance(ftype, dict) and "ref" in ftype:
                lines.append(prefix + f"  * {fname}: ref:{short_id(ftype['ref'])} {c}".rstrip())
            elif isinstance(ftype, str):
                lines.append(prefix + f"  * {fname}: {ftype} {c}".rstrip())
            else:
                lines.append(prefix + f"  * {fname}: any {c}".rstrip())

            # recurse on nested inline types only if it's a dict without "ref"
            if isinstance(ftype, dict) and "ref" not in ftype:
                if len(lines) >= max_lines:
                    break
                lines.extend(render_inline_tree(ftype, indent=indent + 2, max_lines=max_lines - len(lines)))

            if len(lines) >= max_lines:
                break

    # elementType for arrays
    if kind == "array":
        et = inline_obj.get("elementType")
        if isinstance(et, dict) and "ref" in et:
            lines.append(prefix + f"  * items: ref:{short_id(et['ref'])}")
        elif isinstance(et, str):
            lines.append(prefix + f"  * items: {et}")
        elif isinstance(et, dict):
            lines.append(prefix + "  * items:")
            lines.extend(render_inline_tree(et, indent=indent + 2, max_lines=max_lines - len(lines)))

    return lines[:max_lines]


# ----------------------------
# Main: build docs
# ----------------------------

def build_docs(
    ir: Json,
    max_chars_per_chunk: int,
    max_fields_per_chunk: int,
    emit_field_facts: bool,
    emit_glossary_docs: bool,
    emit_inline: bool,
    inline_roots: Optional[List[str]],
    inline_max_lines: int,
) -> List[Json]:
    bundle = ir.get("source_bundle") or {}
    if not isinstance(bundle, dict):
        bundle = {}
    entities = ir.get("entities") or []
    if not isinstance(entities, list):
        entities = []

    bn = bundle.get("name", "bundle")
    sid = bundle.get("source_id", "")
    ver = bundle.get("version", "")
    out_docs: List[Json] = []

    # Index by id for inline root selection and metadata
    ent_by_id: Dict[str, dict] = {}
    for e in entities:
        if isinstance(e, dict) and isinstance(e.get("id"), str):
            ent_by_id[e["id"]] = e

    # Root selection for inline:
    # - If inline_roots provided, treat them as:
    #   - exact entity ids if match
    #   - else match against entity.name or short_id suffix case-insensitively
    root_ids: Set[str] = set()
    if emit_inline:
        if inline_roots:
            wanted = [r.strip() for r in inline_roots if r and r.strip()]
            wl = [w.lower() for w in wanted]
            for eid, e in ent_by_id.items():
                nm = normalize_name(e).lower()
                sid_short = short_id(eid).lower()
                if eid in wanted or nm in wl or sid_short in wl:
                    root_ids.add(eid)
        else:
            # no roots specified => inline any entity that already has annotations.inline
            for eid, e in ent_by_id.items():
                ann = e.get("annotations") or {}
                if isinstance(ann, dict) and "inline" in ann:
                    root_ids.add(eid)

    # Render entity docs
    for eid in sorted(ent_by_id.keys()):
        e = ent_by_id[eid]
        name = normalize_name(e)
        kind = e.get("kind", "")

        refs = sorted(entity_refs(e))
        src_files = collect_source_files(e)

        base_meta = {
            "bundle": bn,
            "source_id": sid,
            "version": ver,
            "entity_id": eid,
            "entity_name": name,
            "kind": kind,
            "refs": refs,
            "source_files": src_files,
        }

        # entity_header
        header_text = render_entity_header(bundle, e)
        out_docs.append({
            "doc_id": f"{bn}::entity_header::{safe(eid)}",
            "type": "entity_header",
            "metadata": base_meta,
            "text": header_text,
        })

        # entity_fields chunks
        fields = e.get("fields") or []
        if isinstance(fields, list) and fields:
            # chunk by max_fields_per_chunk and max_chars_per_chunk
            chunk: List[dict] = []
            chunk_text_preview = ""
            chunks: List[List[dict]] = []

            for f in fields:
                if not isinstance(f, dict):
                    continue
                chunk.append(f)
                # render a small preview to estimate size growth
                chunk_text_preview += render_field_line(f) + "\n"
                if len(chunk) >= max_fields_per_chunk or estimate_len(chunk_text_preview) >= max_chars_per_chunk:
                    chunks.append(chunk)
                    chunk = []
                    chunk_text_preview = ""

            if chunk:
                chunks.append(chunk)

            total = len(chunks)
            for i, ch in enumerate(chunks, start=1):
                txt = render_entity_fields_chunk(bundle, e, ch, i, total)
                out_docs.append({
                    "doc_id": f"{bn}::entity_fields::{safe(eid)}::{i:03d}",
                    "type": "entity_fields",
                    "metadata": {**base_meta, "chunk_index": i, "chunk_total": total, "paths": [f"{name}.{ff.get('name','')}" for ff in ch if isinstance(ff, dict)]},
                    "text": txt,
                })

        # entity_constraints
        cons_txt = render_entity_constraints(bundle, e)
        if cons_txt.strip():
            out_docs.append({
                "doc_id": f"{bn}::entity_constraints::{safe(eid)}",
                "type": "entity_constraints",
                "metadata": base_meta,
                "text": cons_txt,
            })

        # entity_relationships
        rel_txt = render_entity_relationships(bundle, e)
        if rel_txt.strip():
            out_docs.append({
                "doc_id": f"{bn}::entity_relationships::{safe(eid)}",
                "type": "entity_relationships",
                "metadata": base_meta,
                "text": rel_txt,
            })

        # field facts
        if emit_field_facts and isinstance(fields, list):
            for f in fields:
                fact = render_field_fact(bundle, e, f)
                if not fact:
                    continue
                fname = f.get("name", "")
                out_docs.append({
                    "doc_id": f"{bn}::field_fact::{safe(eid)}::{safe(str(fname))}",
                    "type": "field_fact",
                    "metadata": {**base_meta, "field": fname, "path": f"{name}.{fname}"},
                    "text": fact,
                })

        # inline rendering (only for selected roots)
        if emit_inline and eid in root_ids:
            ann = e.get("annotations") or {}
            inline_obj = ann.get("inline") if isinstance(ann, dict) else None
            if inline_obj is not None:
                lines = []
                lines.append(f"# Inlined schema: {name}")
                lines.append(f"EntityId: {eid}")
                lines.append(f"Bundle: {bn} | Source: {sid} {ver} | Kind: {kind}")
                lines.append("")
                outline = render_inline_tree(inline_obj, indent=0, max_lines=inline_max_lines)
                lines.extend(outline)
                txt = "\n".join(lines).strip() + "\n"

                out_docs.append({
                    "doc_id": f"{bn}::entity_inline::{safe(eid)}",
                    "type": "entity_inline",
                    "metadata": {**base_meta, "inline_root": True, "inline_max_lines": inline_max_lines},
                    "text": txt,
                })

    # glossary docs
    if emit_glossary_docs:
        gloss_chunks = render_glossary(bundle, entities=[ent_by_id[eid] for eid in sorted(ent_by_id.keys())], max_chars=max_chars_per_chunk)
        for i, txt in enumerate(gloss_chunks, start=1):
            out_docs.append({
                "doc_id": f"{bn}::glossary::{i:03d}",
                "type": "glossary",
                "metadata": {"bundle": bn, "source_id": sid, "version": ver, "chunk_index": i, "chunk_total": len(gloss_chunks)},
                "text": txt,
            })

    return out_docs


# ----------------------------
# CLI
# ----------------------------

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("bundle_dir", type=str, help="Path to bundle folder containing <name>_ir.json")
    ap.add_argument("--out", type=str, default=None, help="Output directory (default: bundle dir)")
    ap.add_argument("--ir", type=str, default=None, help="Explicit IR file path (default: <bundle>/<name>_ir.json)")

    ap.add_argument("--max-chars-per-chunk", type=int, default=8000, help="Approx max characters per chunk (default 8000)")
    ap.add_argument("--max-fields-per-chunk", type=int, default=30, help="Max fields per entity_fields chunk (default 30)")

    ap.add_argument("--no-field-facts", action="store_true", help="Disable emitting field_fact docs")
    ap.add_argument("--no-glossary", action="store_true", help="Disable emitting glossary docs")

    ap.add_argument("--emit-inline", action="store_true", help="Emit entity_inline docs (uses entity.annotations.inline from IR)")
    ap.add_argument("--inline-roots", type=str, default=None,
                    help="Comma-separated roots to inline. Matches entity id OR entity name OR short id suffix. "
                         "If omitted, emits inline only for entities that already have annotations.inline.")
    ap.add_argument("--inline-max-lines", type=int, default=1200, help="Max outline lines in inline render (default 1200)")

    args = ap.parse_args()

    bundle_dir = Path(args.bundle_dir).resolve()
    out_dir = Path(args.out).resolve() if args.out else bundle_dir

    # Determine bundle name by scanning for *_ir.json if needed
    if args.ir:
        ir_path = Path(args.ir).resolve()
    else:
        # try to find a single *_ir.json file in bundle_dir
        cands = sorted(bundle_dir.glob("*_ir.json"))
        if len(cands) == 1:
            ir_path = cands[0]
        else:
            # fall back to bundle.yaml name if present
            yml = bundle_dir / "bundle.yaml"
            if yml.exists():
                import yaml  # optional import; only needed here
                manifest = yaml.safe_load(yml.read_text(encoding="utf-8")) or {}
                name = manifest.get("name")
                if isinstance(name, str) and name.strip():
                    ir_path = bundle_dir / f"{name.strip()}_ir.json"
                else:
                    raise FileNotFoundError(f"Could not infer IR file. Provide --ir. Candidates: {cands}")
            else:
                raise FileNotFoundError(f"Could not infer IR file. Provide --ir. Candidates: {cands}")

    if not ir_path.exists():
        raise FileNotFoundError(f"IR file not found: {ir_path}")

    ir = read_json(ir_path)
    bundle = ir.get("source_bundle") or {}
    bn = bundle.get("name", safe(ir_path.stem.replace("_ir", "")))

    inline_roots = None
    if args.inline_roots:
        inline_roots = [s.strip() for s in args.inline_roots.split(",") if s.strip()]

    docs = build_docs(
        ir=ir,
        max_chars_per_chunk=max(1000, int(args.max_chars_per_chunk)),
        max_fields_per_chunk=max(1, int(args.max_fields_per_chunk)),
        emit_field_facts=(not args.no_field_facts),
        emit_glossary_docs=(not args.no_glossary),
        emit_inline=bool(args.emit_inline),
        inline_roots=inline_roots,
        inline_max_lines=max(50, int(args.inline_max_lines)),
    )

    out_path = out_dir / f"{bn}_docs.jsonl"
    write_jsonl(out_path, docs)
    print(str(out_path))
    print(f"[render_chunks] wrote {len(docs)} docs")


if __name__ == "__main__":
    main()


# python render_chunks.py /Users/fahed/github/rag-utils/docs/FpML.5.1.13
# this will output: /Users/fahed/github/rag-utils/docs/FpML.5.1.13/fpml_5_13_docs.jsonl
# Tune chunk sizes: python render_chunks.py /.../FpML.5.1.13 --max-fields-per-chunk 20 --max-chars-per-chunk 6000
# Enable inline-root rendering: python render_chunks.py /.../FpML.5.1.13 --emit-inline --inline-roots FxSwap --inline-max-lines 1500
# turn off tiny fields: python render_chunks.py /.../FpML.5.1.13 --no-field-facts

# That’s ready for:

# embeddings (use text)

# metadata filters (use metadata.bundle, metadata.kind, metadata.paths, etc.)